### ISSUE TITLE
Hotkey Rebinding

### ISSUE THREAD

**Issue by hyferg** [hyferg/bonsai-browser-public#6]
Using Option+Space is not an option for some users. Need to make a settings page where  you can rebind keys. Include rebind option in onboarding as well.

**Comment by filipgoc** [comment]
Absolutely. I've been using option+space for Alfred for more than a decade, I'm not gonna even try a new app that tries to occupy that space...

**Comment by hyferg** [comment]
Added in 1.0.7.
